name: Postcommit

permissions:
  actions: write
  contents: write

on:
  pull_request:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.repo.full_name || github.repository }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  postcommit:
    name: Postcommit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v6
      - name: Delete cancelled runs in the same concurrency group
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          BRANCH_NAME="${{ github.head_ref || github.ref_name }}"
          gh run list \
            --workflow "${{ github.workflow }}" \
            --branch "$BRANCH_NAME" \
            --status cancelled \
            --json databaseId \
            --jq ".[].databaseId | select(. != ${{ github.run_id }})" \
            | xargs -I{} gh run delete {}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Setup venv
        run: |
          uv venv
      - name: Install dependencies
        run: |
          uv sync --dev --locked
      - name: Git config
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Formatting the code with Black
        run: |
          uv run black $(git ls-files '*.py')
      - name: Git diff Black changes
        run: |
          git diff HEAD || true
      - name: Git add Black changes
        run: |
          git add $(git ls-files '*.py')
      - id: commit_black
        name: Git commit Black changes
        run: |
          if git diff-index --quiet HEAD; then
            echo "committed=false" >> $GITHUB_OUTPUT
          else
            git commit -m "Formatting using Black"
            echo "committed=true" >> $GITHUB_OUTPUT
          fi
      - name: Check uv.lock is in-sync with pyproject.toml
        run: |
          uv lock --check
      - name: Sync dependencies
        run: |
          uv export --no-dev -o requirements.txt
          uv export --only-dev -o requirements_dev.txt
      - name: Git diff
        run: |
          git diff HEAD || true
      - name: Git add
        run: |
          git add .
      - id: commit_uv_sync
        name: Git commit sync dependency files
        run: |
          if git diff-index --quiet HEAD; then
            echo "committed=false" >> $GITHUB_OUTPUT
          else
            git commit -m "Sync dependencies using uv"
            echo "committed=true" >> $GITHUB_OUTPUT
          fi 
      - name: Git push
        if: steps.commit_black.outputs.committed == 'true' || steps.commit_uv_sync.outputs.committed == 'true'
        run: |
          git push
